FROM crystallang/crystal:0.35.1-alpine
WORKDIR /opt/app
ENV PATH /opt/app/bin:$PATH
COPY . /opt/app
RUN shards update
RUN crystal build --release --static ./worker.cr -o ./worker
CMD ["crystal", "spec"]

FROM alpine:latest  
RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=0 /opt/app/worker .
CMD ["./worker"]  