name: Crystal CI

on:
  push:
    branches: [ master ]

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Login to DigitalOcean Registry
        run: doctl registry login
      
      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          image: dashforge/dashforge
          tags: v1, latest
          registry: registry.digitalocean.com
          dockerfile: Dockerfile
    
      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          image: dashforge/worker
          tags: v1, latest
          registry: registry.digitalocean.com
          dockerfile: Dockerfile

      
